name: fourier

channels:
  - default
  - conda-forge

dependencies:
  - numpy
  - jupyter
  - scipy
  - plotly
  - pandas
  - imageio
  - opencv
  - matplotlib
  - pip

  # Pip must be used to install the Thorcam software python sdk manually